const errorCatalog = [
  {
    id: 'npm-enoent',
    pattern: 'ENOENT',
    title: 'npm ERR! code ENOENT',
    summary: 'A file, folder, or dependency path required by npm is missing.',
    whatHappened: 'Node could not find a file or dependency path that the project expected to exist.',
    why: 'This often happens when the package is not installed, the script path is wrong, or the working directory is incorrect.',
    causes: ['Missing node_modules', 'Wrong folder selected in the terminal', 'Invalid package script path'],
    fixes: ['Run npm install', 'Verify your current directory', 'Check the package.json scripts section'],
    checks: ['Run pwd or Get-Location and confirm the project folder', 'Check that package.json exists', 'Inspect the full npm command for a misspelled path'],
    prevention: 'Run project commands from the folder that contains package.json and keep dependencies installed before starting development.',
    relatedTutorials: ['Install Git', 'Deploy GitHub to Render'],
    commands: ['npm install', 'ls', 'pwd'],
    difficulty: 'Beginner',
  },
  {
    id: 'git-push-rejected',
    pattern: 'rejected',
    title: 'Git push rejected',
    summary: 'The remote branch has changes or rules that prevent this push.',
    whatHappened: 'The remote repository rejected the push because the branch was behind or the remote settings do not match the local state.',
    why: 'Git needs a clean merge path before remote updates can be accepted.',
    causes: ['Local branch is not synced with origin', 'Protected branch rules', 'Merge conflict or incorrect remote'],
    fixes: ['git pull --rebase origin main', 'Resolve merge conflicts', 'Check GitHub branch protections'],
    checks: ['Run git status to inspect the current branch', 'Run git remote -v to verify the destination', 'Read the complete rejection message for branch rules'],
    prevention: 'Pull and review remote changes before pushing, especially when working with a shared main branch.',
    relatedTutorials: ['Connect Your Code to GitHub'],
    commands: ['git pull --rebase origin main', 'git push origin main'],
    difficulty: 'Intermediate',
  },
  {
    id: 'render-build-failed',
    pattern: 'build failed',
    title: 'Render build failed',
    summary: 'Render could not finish installing or building the deployed application.',
    whatHappened: 'Render could not complete the install or build stage for your project.',
    why: 'The runtime, build commands, or dependencies were not matching the project configuration.',
    causes: ['Missing dependency file', 'Build script issue', 'Wrong runtime or branch'],
    fixes: ['Check Render build logs', 'Verify package.json and start scripts', 'Confirm environment variables'],
    checks: ['Confirm the configured root directory', 'Run the build command locally', 'Compare Node and package manager versions with Render'],
    prevention: 'Keep the deployment command documented, test production builds locally, and configure required environment variables in Render.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['npm install', 'npm run build', 'npm start'],
    difficulty: 'Intermediate',
  },
  {
    id: 'git-merge-conflict',
    pattern: 'CONFLICT',
    title: 'Git merge conflict',
    summary: 'A merge conflict stopped the automatic branch combine process.',
    whatHappened: 'Git detected competing edits in the same file and paused the merge before committing.',
    why: 'The branch you merged and the current branch changed the same lines in different ways.',
    causes: ['Two branches changed the same file', 'Unresolved edits in a shared file', 'Manual conflict in the same code block'],
    fixes: ['Open the conflicted files and choose the correct lines', 'git add the resolved file', 'git commit the merge'],
    checks: ['Run git status', 'Inspect the conflict markers', 'Compare with the last known good branch'],
    prevention: 'Pull the latest main branch and communicate changes before editing shared files.',
    relatedTutorials: ['Connect Your Code to GitHub'],
    commands: ['git status', 'git add .', 'git commit -m "Resolve merge conflict"'],
    difficulty: 'Intermediate',
  },
  {
    id: 'npm-module-not-found',
    pattern: 'Cannot find module',
    title: 'Node module missing',
    summary: 'A dependency required by the Node process is not installed in the project.',
    whatHappened: 'Node tried to require an installed package but could not find it in the dependency tree.',
    why: 'The dependency was never installed, the install failed, or the package is missing from the lockfile snapshot.',
    causes: ['Dependencies not installed', 'Wrong package manager', 'Missing package in package.json'],
    fixes: ['npm install', 'npm ci', 'Verify package.json dependency names'],
    checks: ['Run npm ls', 'Verify node_modules exists', 'Check package.json and package-lock.json'],
    prevention: 'Install dependencies in a clean environment and commit package-lock.json when sharing the project.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['npm install', 'npm ls express', 'npm run start'],
    difficulty: 'Intermediate',
  },
  {
    id: 'port-in-use',
    pattern: 'EADDRINUSE',
    title: 'Port already in use',
    summary: 'The local development server could not bind to the requested port because another process is already using it.',
    whatHappened: 'The server attempted to listen on the same port and failed because that address was occupied.',
    why: 'A previous development server, process, or background task is still holding the port.',
    causes: ['Development server left running', 'Another app is using port 3000', 'Port forwarding conflict'],
    fixes: ['Stop the old process', 'Change the server port', 'Kill the process holding the port'],
    checks: ['Run netstat -ano | findstr :3000', 'Use lsof -i :3000', 'Check package scripts for an alternate port'],
    prevention: 'Always stop active dev servers before restarting or configure a consistent port per project.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev -- --port 3001', 'netstat -ano | findstr :3000', 'taskkill /PID 1234'],
    difficulty: 'Beginner',
  },
  {
    id: 'postgres-connection-refused',
    pattern: 'ECONNREFUSED',
    title: 'PostgreSQL connection refused',
    summary: 'The application could not connect to PostgreSQL because the database server was not listening.',
    whatHappened: 'The code reached the database host and port but the server refused the connection.',
    why: 'PostgreSQL is not running, the port is wrong, or the database service is not reachable from the local environment.',
    causes: ['PostgreSQL service stopped', 'Wrong port', 'Wrong host or environment config'],
    fixes: ['Start PostgreSQL', 'Verify DATABASE_URL', 'Check firewall or docker network settings'],
    checks: ['Check service status', 'Confirm localhost:5432', 'Confirm database credentials'],
    prevention: 'Document the database host, port, username, password, and service startup command in local environment setup.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['pg_isready', 'psql -U postgres', 'echo $DATABASE_URL'],
    difficulty: 'Intermediate',
  },
  {
    id: 'missing-database-url',
    pattern: 'DATABASE_URL is not defined',
    title: 'Missing DATABASE_URL environment variable',
    summary: 'The app could not access the database because an expected environment variable was missing.',
    whatHappened: 'The application started and then failed at runtime because the connection string variable was not defined.',
    why: 'The required environment value was not loaded into the deployment or development shell.',
    causes: ['Missing .env entry', 'Deployment variable not configured', 'Local shell session did not reload variables'],
    fixes: ['Add DATABASE_URL to the environment manager', 'Restart the process after setting the variable', 'Confirm the value is loaded in the shell'],
    checks: ['Run env | grep DATABASE_URL', 'Check the deployment settings page', 'Review .env.example'],
    prevention: 'Template environment variables in a project README and validate them before deployment.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['echo $DATABASE_URL', 'cp .env.example .env', 'npm run dev'],
    difficulty: 'Intermediate',
  },
  {
    id: 'cors-blocked',
    pattern: 'CORS policy',
    title: 'CORS blocked by browser policy',
    summary: 'The frontend could not receive a response from an API because the browser policy rejected the origin.',
    whatHappened: 'The app requested a remote resource from a different origin without an allowed response header.',
    why: 'The server-side API did not include Access-Control-Allow-Origin or did not permit the local frontend origin.',
    causes: ['Missing CORS headers', 'Wrong API base URL', 'API server not configured for local development'],
    fixes: ['Add CORS headers on the API', 'Use the correct origin allowed list', 'Proxy API requests locally'],
    checks: ['Inspect response headers', 'Check browser network request', 'Confirm frontend origin matches the allowed list'],
    prevention: 'Keep an approved CORS policy and test local API requests against the same origin or configured allowlist.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl -I https://api.example.com/users', 'npm run dev', 'vite.config.js'],
    difficulty: 'Intermediate',
  },
  {
    id: 'docker-node-not-found',
    pattern: 'node:22',
    title: 'Docker image tag not found',
    summary: 'Docker could not find the base image tag while building the container.',
    whatHappened: 'The build process tried to pull a tag that was not available in the configured registry.',
    why: 'The requested image tag is missing, outdated, or the registry has been moved.',
    causes: ['Wrong tag or image name', 'Registry unavailable', 'Private registry access issue'],
    fixes: ['Use a valid base image tag', 'Check docker pull access', 'Update the Dockerfile base image'],
    checks: ['Run docker pull node:22', 'Check image tag support', 'Verify registry credentials'],
    prevention: 'Pin verified images and test builds locally before pushing infrastructure changes.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['docker build -t my-app .', 'docker pull node:22', 'docker images'],
    difficulty: 'Intermediate',
  },
  {
    id: 'react-map-undefined',
    pattern: 'reading map',
    title: 'React cannot read map of undefined',
    summary: 'A React component tried to render an array mapping from a missing data value.',
    whatHappened: 'The render pipeline attempted to call .map on an undefined object in a component branch.',
    why: 'The component render expectation did not match the data shape coming from the API or local state.',
    causes: ['Missing API response field', 'State not initialized', 'Component is rendering before data loads'],
    fixes: ['Guard with default data', 'Load data before rendering', 'Check the API response shape'],
    checks: ['Inspect state and props', 'Log the API data', 'Confirm the payload field exists'],
    prevention: 'Normalize data before rendering and add guard clauses when a list may arrive late.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev', 'curl /api/users', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'python-keyerror',
    pattern: 'KeyError',
    title: 'Python KeyError',
    summary: 'The Python script accessed a dictionary key that was not present.',
    whatHappened: 'A dictionary lookup used a key that the payload did not include to the script path.',
    why: 'The requested data field is missing from the object or the data shape changed.',
    causes: ['Missing key in incoming payload', 'Wrong field name', 'Different object structure'],
    fixes: ['Use .get() or check the key exists', 'Validate input data', 'Log the request payload'],
    checks: ['Print the dictionary keys', 'Confirm the external payload field', 'Validate before the read'],
    prevention: 'Use defensive access patterns and validate required keys before reading them.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['python app.py', 'print(payload.keys())', 'python -m json.tool'],
    difficulty: 'Intermediate',
  },
  {
    id: 'sql-column-does-not-exist',
    pattern: 'column "username" does not exist',
    title: 'SQL column missing',
    summary: 'The query referenced a database column that is not present in the schema.',
    whatHappened: 'The SQL statement tried to select a column that the table does not define.',
    why: 'The table schema and the query are out of sync or the column has been renamed.',
    causes: ['Wrong column name', 'Migration not applied', 'Schema changed without query update'],
    fixes: ['Use the existing column name', 'Run database migrations', 'Update the query to the new schema'],
    checks: ['Inspect the table schema', 'Review the SELECT statement', 'Check migration history'],
    prevention: 'Keep the database migration file and query code aligned and test SQL queries against the schema before shipping.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['psql -c "\dt"', 'psql -c "\d users"', 'npm run migrate'],
    difficulty: 'Advanced',
  },
  {
    id: 'json-syntax',
    pattern: 'JSON.parse error',
    title: 'JSON parsing error',
    summary: 'A JSON request or file could not be parsed because the shape or delimiter syntax is invalid.',
    whatHappened: 'The application attempted to parse a JSON string but found a syntax error in the input.',
    why: 'An extra comma or unmatched token ended the JSON payload unexpectedly.',
    causes: ['Trailing comma in JSON', 'Missing quotes', 'Wrong data type or extra bracket'],
    fixes: ['Validate JSON locally', 'Remove trailing commas', 'Parse the payload before app usage'],
    checks: ['Use JSON validator tools', 'Review the exact input position', 'Confirm payload keys match the expected schema'],
    prevention: 'Validate JSON on the client or server before shipping your configuration or API payload.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['node -e "JSON.parse(data)"', 'jq . config.json', 'curl /api/config'],
    difficulty: 'Intermediate',
  },
  {
    id: 'production-service-unavailable',
    pattern: '503 Service Unavailable',
    title: 'Production service unavailable',
    summary: 'The deployment health check failed and the production service returned a 503 response.',
    whatHappened: 'The production service could not respond correctly because its dependency chain or runtime health check failed.',
    why: 'The database or other service dependency was unavailable during the health check.',
    causes: ['Database timeout', 'Health check failing', 'Resource exhaustion'],
    fixes: ['Check database connectivity', 'Review deployment logs', 'Retry the health endpoint after restoring dependencies'],
    checks: ['Check /api/health', 'Inspect infrastructure logs', 'Confirm database credentials'],
    prevention: 'Add readiness health-checks, database fail-safe logs, and production rollback plans before deployment.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['curl /api/health', 'kubectl logs', 'npm run start'],
    difficulty: 'Advanced',
  },
  {
    id: 'vite-build-failed',
    pattern: 'vite build',
    title: 'Vite production build failed',
    summary: 'The Vite bundler stopped because the source or syntax path could not be built for production.',
    whatHappened: 'Vite reached the production build phase and found a dependency, syntax, or import problem.',
    why: 'The code import graph or the JSX/TS syntax is not valid for the installed build tooling version.',
    causes: ['Syntax error in a source file', 'Invalid import path', 'Version mismatch between Vite and dependencies'],
    fixes: ['Run npm run build locally and read the first filename in the error', 'Fix the source syntax error', 'Confirm the installed Vite and package versions match'],
    checks: ['Run npm ls vite', 'Read the file and line number from the Vite error', 'Check package.json scripts and dependencies'],
    prevention: 'Run the production build locally before deploying and keep the Node, Vite, and package versions aligned.',
    relatedTutorials: ['Deploy GitHub to Render', 'Troubleshooting'],
    commands: ['npm run build', 'npm ls vite', 'npm install'],
    difficulty: 'Intermediate',
  },
  {
    id: 'eacces-permission-denied',
    pattern: 'EACCES',
    title: 'Permission denied while accessing a file or port',
    summary: 'The process could not write, bind, or access a resource because of a permission restriction.',
    whatHappened: 'The terminal process or server tried to read or write a path or resource without the right permission level.',
    why: 'The process user does not own the file directory or cannot bind to the requested network resource.',
    causes: ['Directory owned by another user', 'Docker or root-user mismatch', 'System port blocked by OS permissions'],
    fixes: ['Use an administrator shell', 'Fix file ownership with chown', 'Change to a non-reserved local port'],
    checks: ['Check file ownership', 'Confirm which user launched the command', 'Inspect the port and process owner'],
    prevention: 'Run local development commands with the correct user, keep Docker groups configured, and avoid writing into protected folders.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['sudo chown -R $USER .', 'ls -la', 'netstat -ano | findstr :3000'],
    difficulty: 'Intermediate',
  },
  {
    id: 'module-not-found',
    pattern: 'ERR_MODULE_NOT_FOUND',
    title: 'Module import path not found',
    summary: 'A source import path cannot be resolved by the bundler or runtime.',
    whatHappened: 'The project tried to import a file or package path that did not exist at that exact location.',
    why: 'The import path is wrong, the file was renamed, or the dependency was never added to the package manifest.',
    causes: ['Wrong relative import path', 'Missing package dependency', 'Moved file with stale import reference'],
    fixes: ['Check the import string and file location', 'Install the missing package', 'Use a clean import path from the project root'],
    checks: ['Review the path in the import line', 'Check file existence in the source tree', 'Run npm ls or pnpm why'],
    prevention: 'Keep import paths relative to the actual folder structure and validate workspace imports after renames or refactors.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm install', 'ls src', 'grep -R "import .*" src'],
    difficulty: 'Intermediate',
  },
  {
    id: 'deployment-404-route',
    pattern: '404 Not Found',
    title: 'Static route or deploy asset returns 404',
    summary: 'The deployed website route or asset file is missing the expected route fallback or public asset path.',
    whatHappened: 'The server or host returned a 404 page for a route or asset that should have been built or published.',
    why: 'The route fallback or public asset directory is missing, and the host cannot find the requested path.',
    causes: ['Missing static public folder', 'Wrong base path', 'Single-page route fallback not configured'],
    fixes: ['Add a public/_redirects or netlify rewrite rule', 'Confirm the asset path exists in the build output', 'Check the production base path'],
    checks: ['List the build folder output', 'Inspect public asset generation', 'Confirm the route fallback or rewrites setting'],
    prevention: 'Test the production preview locally and verify the build output directory has a route fallback before publishing.',
    relatedTutorials: ['Deploy GitHub to Render', 'Troubleshooting'],
    commands: ['npm run build', 'ls dist', 'curl https://your-domain/path'],
    difficulty: 'Intermediate',
  },
  {
    id: 'vite-import-resolution',
    pattern: 'Failed to resolve import',
    title: 'Vite import resolution error',
    summary: 'Vite could not find an imported file or component path during dev startup.',
    whatHappened: 'The Vite development server failed to resolve a source import while loading the app entry point.',
    why: 'The import string points to a file that does not exist, was renamed, or uses the wrong casing or folder path.',
    causes: ['Wrong relative import path', 'File rename without import update', 'Case mismatch between import and file'],
    fixes: ['Confirm the target file exists', 'Fix the import path casing and folder location', 'Restart the Vite server after correcting the import'],
    checks: ['Inspect the import line in the error output', 'Check the file name and casing in src/components', 'Run ls or file search for the imported component'],
    prevention: 'Keep import paths consistent with the actual file tree and test the app after moving or renaming files.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev', 'ls src/components', 'grep -R "Navbar" src'],
    difficulty: 'Intermediate',
  },
  {
    id: 'react-invalid-hook-call',
    pattern: 'Invalid hook call',
    title: 'React hook call error',
    summary: 'A hook was called in a place where React components or hook contexts are not allowed.',
    whatHappened: 'React detected that a hook was invoked outside the function component flow or from multiple React copies.',
    why: 'The app may have duplicate React installations or a hook was called in a helper or non-component context.',
    causes: ['Duplicate React dependency', 'Hook called outside component', 'Mismatched React versions'],
    fixes: ['Ensure a single React instance is installed', 'Move the hook call into a component body', 'Check package versions and dependency tree'],
    checks: ['Inspect import resolution for React', 'Run npm ls react react-dom', 'Verify the function component shape'],
    prevention: 'Keep React dependencies synchronized and place hooks only inside valid component or custom hook functions.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm ls react react-dom', 'npm install', 'npm run dev'],
    difficulty: 'Intermediate',
  },
  {
    id: 'react-list-key-warning',
    pattern: 'Each child in a list should have a unique',
    title: 'React list key warning',
    summary: 'A React list render did not define a stable unique key for every item.',
    whatHappened: 'The component rendered an array of child nodes and React warned that keys were missing or duplicated.',
    why: 'The item map function did not assign a unique value such as an id or slug.',
    causes: ['Duplicate key value', 'Missing key property', 'Array item identifier not unique'],
    fixes: ['Use a unique id or slug from the data source', 'Move keys to the top-level list item element', 'Avoid duplicating tutorial keys'],
    checks: ['Inspect the map callback output', 'Verify the source object id field exists', 'Confirm each child name is unique'],
    prevention: 'Use stable values such as database ids or slugs as React keys for data-driven list rendering.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev', 'grep -R "map(" src', 'npm run build'],
    difficulty: 'Beginner',
  },
  {
    id: 'react-state-update-unmounted',
    pattern: 'Can\'t perform a React state update on an unmounted component',
    title: 'State update after component unmount',
    summary: 'An async action finished after the component had already been removed from the UI.',
    whatHappened: 'The code scheduled a state update in a promise, timer, or fetch callback that still fired after the component had been disposed.',
    why: 'A cleanup path was missing and the request or interval kept updating a component that no longer exists.',
    causes: ['Async request completes after unmount', 'Timer not cleared', 'Missing cancellation or ignore flag'],
    fixes: ['Cancel timers or requests in cleanup', 'Use a mounted flag or AbortController', 'Prevent state updates after unmount'],
    checks: ['Inspect the cleanup function', 'Review async service calls in useEffect', 'Confirm clearInterval or request abort handling'],
    prevention: 'Guard async work with cleanup logic and cancellation so state changes do not run once a component is gone.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev', 'npm run build', 'grep -R "setInterval" src'],
    difficulty: 'Intermediate',
  },
  {
    id: 'react-render-loop',
    pattern: 'RENDER LOOP DETECTED',
    title: 'Infinite render loop',
    summary: 'A component repeatedly re-renders because state is changed inside the render or effect dependency cycle.',
    whatHappened: 'A state setter inside an effect fired continuously, causing repeated rendering without a dependency guard.',
    why: 'The effect or render expression updates state without limiting when or how often it runs.',
    causes: ['Effect without dependency array', 'setState in render path', 'State reset on every render'],
    fixes: ['Add a dependency array to useEffect', 'Move state updates out of render', 'Guard state updates with a conditional check'],
    checks: ['Inspect the useEffect body for setProjects', 'Confirm the dependency array and render conditions', 'Limit the render count by reducing side effects'],
    prevention: 'Keep render pure and make effects derive from dependencies instead of forcing new state every time.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run dev', 'grep -R "setProjects" src', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'localstorage-quota',
    pattern: 'QuotaExceededError',
    title: 'Local storage quota exceeded',
    summary: 'The browser refused to save workspace state because the origin storage quota was full.',
    whatHappened: 'The app tried to persist a large amount of local data under a workspace storage key and the browser rejected it.',
    why: 'Local storage is small and quotas are per origin, so saved workspace data can exceed the allowed capacity.',
    causes: ['Workspace data too large', 'Old cached data not cleared', 'Too many saved records'],
    fixes: ['Reset the workspace storage key', 'Trim large cached records', 'Store large data outside localStorage'],
    checks: ['Inspect localStorage usage in the browser', 'Clear the stored devdeploy_workspace value', 'Confirm data size before writing again'],
    prevention: 'Keep workspace data compact and store heavy output in a server-backed object store or a compressed strategy.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['localStorage.clear()', 'getItem("devdeploy_workspace")', 'sessionStorage.clear()'],
    difficulty: 'Intermediate',
  },
  {
    id: 'corrupted-workspace-storage',
    pattern: 'Unexpected end of JSON input',
    title: 'Corrupted local workspace data',
    summary: 'The app failed to restore a saved workspace state because the stored JSON payload was truncated or malformed.',
    whatHappened: 'The app attempted to parse a saved workspace object but the browser loaded an incomplete JSON payload.',
    why: 'The local storage entry was overwritten, partially saved, or saved during a crash.',
    causes: ['Interrupted save', 'Partial update', 'Manual data corruption'],
    fixes: ['Restore backup', 'Reset workspace storage', 'Recover a saved project snapshot'],
    checks: ['Inspect the localStorage key', 'Check for backup data', 'Confirm the JSON parser sees a valid object'],
    prevention: 'Guard writes with a backup and write workspace data atomically or in a versioned serialized format.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['localStorage.removeItem("devdeploy_workspace")', 'JSON.parse(rawData)', 'git restore .'],
    difficulty: 'Intermediate',
  },
  {
    id: 'api-retry-loop',
    pattern: 'Automatic retry loop detected',
    title: 'Infinite API retry loop',
    summary: 'The client or outage monitor kept retrying a failing request without a bounded retry policy.',
    whatHappened: 'An API client tried to recover from a 503 response repeatedly, reaching a retry loop with no maximum limit.',
    why: 'The retry policy did not cap attempts and did not stop once the backend or network dependency became usable again.',
    causes: ['No retry limit set', 'Broken health endpoint', 'Flapping dependency'],
    fixes: ['Add a max retry limit', 'Back off with a jittered delay', 'Inspect the upstream service health'],
    checks: ['Check the request retry policy', 'Inspect logs for repeated 503 attempts', 'Confirm the endpoint returns a valid response'],
    prevention: 'Cap retry attempts and add circuit-breaker logic around failing API dependencies.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl /api/projects', 'npm run dev', 'grep -R "retry" src'],
    difficulty: 'Advanced',
  },
  {
    id: 'auth-token-expired',
    pattern: 'TOKEN_EXPIRED',
    title: 'Authentication token expired',
    summary: 'The API request failed because the access token was no longer valid.',
    whatHappened: 'The application sent an expired token to the API and the server refused the request with a 401 response.',
    why: 'The token lifetime ended or a refresh flow did not issue an updated token before the next protected call.',
    causes: ['Expired user session', 'Stale stored token', 'Refresh token failed'],
    fixes: ['Refresh the authentication token', 'Re-login to the application', 'Confirm the token refresh workflow'],
    checks: ['Inspect the auth cookie or Bearer token age', 'Confirm the refresh endpoint response', 'Check the request header'],
    prevention: 'Refresh the token before it expires and store the new token only after the server confirms the refresh.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl -H "Authorization: Bearer <token>" /api/profile', 'npm run dev', 'refresh-token'],
    difficulty: 'Intermediate',
  },
  {
    id: 'jwt-invalid-signature',
    pattern: 'invalid signature',
    title: 'JWT invalid signature',
    summary: 'The JSON Web Token could not be trusted because its cryptographic signature did not match.',
    whatHappened: 'The app tried to validate a token that was signed with a different secret key or had been altered.',
    why: 'The token came from a different environment, was corrupted, or was generated by a mismatched secret.',
    causes: ['Wrong JWT secret', 'Token altered in transit', 'Cross-environment token reuse'],
    fixes: ['Regenerate the token with the correct secret', 'Verify the token source environment', 'Rotate credentials or signing secret'],
    checks: ['Compare the token issuer and exp fields', 'Verify the JWT secret and environment config', 'Inspect the middleware authentication logs'],
    prevention: 'Keep separate JWT secrets per environment and avoid sharing tokens across environments.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['jwt decode <token>', 'echo $JWT_SECRET', 'npm run dev'],
    difficulty: 'Advanced',
  },
  {
    id: 'api-rate-limit',
    pattern: 'HTTP 429 Too Many Requests',
    title: 'API rate limit exceeded',
    summary: 'The API rejected the request because the request rate exceeded the configured limit.',
    whatHappened: 'The client submitted too many requests in a short window and the service returned a 429 response.',
    why: 'The frontend or a deployment process hit the endpoint repeatedly without a cooldown or queue.',
    causes: ['Too many generate requests', 'Endpoint burst traffic', 'Missing backoff or throttling'],
    fixes: ['Wait for Retry-After seconds', 'Throttle the request loop', 'Use the API provider rate limit policy'],
    checks: ['Confirm headers include Retry-After', 'Validate endpoint request count', 'Review request frequency and traffic logs'],
    prevention: 'Add client throttles, queue generation jobs, and exponential backoff around rate-limited APIs.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl -I /api/generate', 'npm run dev', 'grep -R "retryAfter" src'],
    difficulty: 'Intermediate',
  },
  {
    id: 'db-migration-error',
    pattern: 'relation "users" does not exist',
    title: 'Database migration dependency error',
    summary: 'A migration stopped because an expected database table or relation did not already exist.',
    whatHappened: 'The migration sequence tried to add a table relationship that referenced a schema object that had not been created earlier.',
    why: 'The migration order or the schema setup is out of sync with the query sequence.',
    causes: ['Missing migration dependency', 'Table creation order issue', 'Schema changed without forwarding migration'],
    fixes: ['Run migrations in the required order', 'Create the missing table or relation', 'Review migration files and dependency chain'],
    checks: ['List migration files in sequence', 'Run psql schema check', 'Inspect the migration log'],
    prevention: 'Keep migrations ordered and idempotent, and run schema snapshot tests before production deploys.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['npm run migrate', 'psql -c "\dt"', 'psql -c "\d users"'],
    difficulty: 'Advanced',
  },
  {
    id: 'db-duplicate-entry',
    pattern: 'duplicate key value violates unique constraint',
    title: 'Database duplicate key violation',
    summary: 'The database rejected a write because a unique column value already existed.',
    whatHappened: 'The SQL insert attempted to create a user row with an email address that was already associated with another row in the database.',
    why: 'The application accepted a duplicate value for a unique field or a user lifecycle object already existed in the database.',
    causes: ['Duplicate email or username', 'Missing idempotent save checks', 'Data import repeated'],
    fixes: ['Use an existing record instead of insert', 'Update the duplicate row', 'Normalize the incoming unique field'],
    checks: ['Confirm the database unique constraints', 'Inspect the user table and duplicate known values', 'Review the insert payload'],
    prevention: 'Validate unique user inputs and add a deduplication or idempotent save step before calling writes to the database.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['psql -c "SELECT * FROM users WHERE email = \"developer@example.com\""', 'npm run migrate', 'git status'],
    difficulty: 'Intermediate',
  },
  {
    id: 'db-foreign-key-error',
    pattern: 'violates foreign key constraint',
    title: 'SQL foreign key constraint error',
    summary: 'The database rejected a write because the related parent row was not present.',
    whatHappened: 'An insert or update referenced a row id in another table that the parent table did not contain.',
    why: 'The relationship was created before the parent object existed or the id was generated in another environment.',
    causes: ['Missing user row', 'Wrong user id in the payload', 'Unseeded parent table'],
    fixes: ['Create or fetch the parent row first', 'Validate user_id before insert', 'Check the row was committed in the same transaction'],
    checks: ['Inspect the parent table keys', 'Trace the request payload user_id', 'Confirm database write order'],
    prevention: 'Validate foreign keys before write and document a relationship-safe data creation order for the application.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['psql -c "\d projects"', 'psql -c "\d users"', 'npm run migrate'],
    difficulty: 'Advanced',
  },
  {
    id: 'db-transaction-failed',
    pattern: 'TRANSACTION FAILED',
    title: 'SQL transaction roll back',
    summary: 'A multi-step database transaction stopped and all writes were rolled back.',
    whatHappened: 'The transaction inserted user, profile, and project rows but hit a constraint failure before the final commit',
    why: 'The data model or write sequence was broken by a duplicate key or a missing required relation.',
    causes: ['Duplicate value during insert', 'Constraint violation', 'Partial row creation order mismatch'],
    fixes: ['Inspect the failing insert and constraint', 'Make the transaction idempotent', 'Review the rollback and retry flow'],
    checks: ['Find the first failing statement', 'Look for duplicate constraint message', 'Review transaction boundaries'],
    prevention: 'Ensure write operations validate constraints before applying the full transaction and check rollback behavior in test data.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['psql -c "\d users"', 'npm run migrate', 'git status'],
    difficulty: 'Advanced',
  },
  {
    id: 'node-version-mismatch',
    pattern: 'Unsupported Node.js version',
    title: 'Node version mismatch',
    summary: 'The project requires a newer Node.js runtime than the command shell provided.',
    whatHappened: 'The package or build expected Node version 20+ but the current environment was still Node 18.',
    why: 'The workspace did not switch to the correct runtime before running the project command.',
    causes: ['Version manager not activated', 'Wrong shell session', 'Project engine field changed'],
    fixes: ['Install or use the required Node version', 'Run nvm use or a project version manager', 'Create a matching package engine list'],
    checks: ['Run node -v', 'Confirm package.json engines', 'Check the shell profile setup'],
    prevention: 'Document the minimum Node version in the project and test setup instructions before a deployment workflow.',
    relatedTutorials: ['Install Git', 'Deploy GitHub to Render'],
    commands: ['node -v', 'npm -v', 'nvm use 20'],
    difficulty: 'Intermediate',
  },
  {
    id: 'npm-peer-conflict',
    pattern: 'ERESOLVE unable to resolve dependency tree',
    title: 'NPM peer dependency conflict',
    summary: 'NPM could not find a compatible dependency combination between the installed packages.',
    whatHappened: 'The dependency tree requested a package version that was incompatible with the react or peer version range in the project.',
    why: 'Two packages require different peer versions or a dependency major version constraint is not satisfied.',
    causes: ['Package peer version mismatch', 'Wrong package manager lock', 'Old dependency tree'],
    fixes: ['Align peer dependencies', 'Update or downgrade package versions', 'Use npm install --legacy-peer-deps only as a last resort'],
    checks: ['Run npm ls react', 'Inspect npm error peer version details', 'Confirm package-lock and package.json versions'],
    prevention: 'Keep peer requirements in sync and run dependency tree checks when upgrading frontend libraries.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm ls react', 'npm install', 'npm audit'],
    difficulty: 'Advanced',
  },
  {
    id: 'typescript-type-error',
    pattern: 'TS2322',
    title: 'TypeScript type mismatch',
    summary: 'The TypeScript compiler found a variable type that did not satisfy the property or prop contract.',
    whatHappened: 'The TypeScript checker saw a number being passed where the component prop expected a string.',
    why: 'The function or component signature and the supplied argument had diverged.',
    causes: ['Wrong data source type', 'Prop shape mismatch', 'Type annotation missing'],
    fixes: ['Convert the value to the expected type', 'Pass the right property from the model', 'Add and verify the type annotation'],
    checks: ['Inspect the value and component signature', 'Run tsc --noEmit', 'Confirm source data is typed correctly'],
    prevention: 'Lift types into a shared model and validate data objects before passing them into UI props.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run build', 'npx tsc --noEmit', 'npm run lint'],
    difficulty: 'Intermediate',
  },
  {
    id: 'eslint-no-unused-vars',
    pattern: 'no-unused-vars',
    title: 'ESLint unused variable and missing dependency warning',
    summary: 'The lint run detected a variable or hook dependency that was not being used or referenced correctly.',
    whatHappened: 'The project lint step caught a state variable or imported hook dependency that should be included or removed.',
    why: 'The file includes a variable that is no longer used in the render path or a hook effect is missing one of its dependency values.',
    causes: ['Unused variable', 'Effect dependency omitted', 'Stale project imports'],
    fixes: ['Remove unused variables or import them intentionally', 'Add the missing dependency to the effect array', 'Run lint after cleanup'],
    checks: ['Review the file lines with lint output', 'Inspect the effect dependencies', 'Compare the component render and data flow'],
    prevention: 'Run lint locally before a deployment and keep hook dependencies in a strict, documented order.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run lint', 'npm run build', 'npm run dev'],
    difficulty: 'Beginner',
  },
  {
    id: 'vite-env-prefix',
    pattern: 'Client-side environment variables must use',
    title: 'Vite environment variable prefix error',
    summary: 'The configuration used a browser-environment variable name without the required VITE_ prefix.',
    whatHappened: 'The application tried to access a front-end environment variable named API_URL, but Vite only exposes variables starting with VITE_.',
    why: 'The app expected an environment variable to be available in the browser, but the variable key was not marked for client access.',
    causes: ['Environment variable missing VITE_ prefix', 'Frontend variable not public', 'Wrong variable naming convention'],
    fixes: ['Rename API_URL to VITE_API_URL', 'Confirm that the variable is available in the frontend build', 'Restart the Vite server when changing environment files'],
    checks: ['Check .env and Vite config', 'Confirm the runtime value in the browser', 'Review the environment variable naming policy'],
    prevention: 'Use VITE_ prefixes for any browser-visible variables and document the environment variable list in the project template.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['grep -R "API_URL" .', 'echo $VITE_API_URL', 'npm run dev'],
    difficulty: 'Intermediate',
  },
  {
    id: 'prod-shift-env-mismatch',
    pattern: '2 required production variables are missing',
    title: 'Production environment mismatch',
    summary: 'The production environment is missing application values that the development environment already had.',
    whatHappened: 'The deployment process compared environment keys between dev and prod and found that production variables were absent.',
    why: 'The project configuration path or deployment environment list was not copied to the production workspace.',
    causes: ['Missing production .env keys', 'Production config not linked', 'Deployment config not redeployed'],
    fixes: ['Add the required production variables', 'Validate the production service settings page', 'Restart the deployment after environment sync'],
    checks: ['Compare development vs production environment keys', 'Inspect Render or host environment settings', 'Review the deployment log for the missing values'],
    prevention: 'Keep a production environment checklist and run an environment validation command before each release.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['env | grep DATABASE_URL', 'curl /api/config', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'spa-static-hosting-404',
    pattern: 'The server could not find: /dashboard',
    title: 'SPA route fallback or static hosting rewrite error',
    summary: 'The host returned a 404 page for a client routing URL that requires a fallback rewrite rule.',
    whatHappened: 'The site uses client-side routing, but the static hosting provider or server returned a route-level 404 instead of the app shell.',
    why: 'The deploy target did not include a fallback to the HTML entry point for client routes.',
    causes: ['Missing SPA rewrite rule', 'Route file not generated', 'Host not configured for client routes'],
    fixes: ['Add a rewrite rule or fallback route to the app index file', 'Use a SPA-aware static host setting', 'Check the route output directory'],
    checks: ['Inspect proxy or rewrite files', 'Run curl to the route path', 'Check the route path in deployment settings'],
    prevention: 'Deploy with a configured SPA fallback and run an actual production preview of a deep link route.',
    relatedTutorials: ['Deploy GitHub to Render', 'Troubleshooting'],
    commands: ['curl https://example.com/dashboard', 'ls dist', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'mixed-content-blocked',
    pattern: 'Mixed Content',
    title: 'HTTPS mixed content blocked',
    summary: 'The page was loaded securely but attempted to load a resource over an insecure HTTP connection.',
    whatHappened: 'The secure website loaded a resource whose origin was plain HTTP, and the browser blocked the request.',
    why: 'The app or API browser origin points to a non-HTTPS resource even though the page is served over HTTPS.',
    causes: ['HTTP API URL on HTTPS page', 'Old base URL in config', 'Mixed asset or image URL'],
    fixes: ['Use HTTPS API URLs', 'Update API proxy and asset routes', 'Replace insecure assets'],
    checks: ['Inspect the protocol in the asset URL', 'Inspect network requests in DevTools', 'Confirm the API host is configured for HTTPS'],
    prevention: 'Keep all API, image, font, and asset references on the same secure origin and enforce HTTPS in build config.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl -I https://api.example.com/projects', 'grep -R "http://" src', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'websocket-502',
    pattern: 'Unexpected response code: 502',
    title: 'WebSocket failure',
    summary: 'The browser could not establish a long-lived WebSocket connection because the upstream endpoint returned an unexpected gateway error.',
    whatHappened: 'The client attempted a secure WebSocket connection and the server or proxy gateway returned a 502 instead of upgrading the connection.',
    why: 'The reverse proxy, backend socket route, or upstream host did not understand or properly pass the WebSocket upgrade request.',
    causes: ['Reverse proxy misconfiguration', 'Missing WebSocket headers', 'Backend unavailable'],
    fixes: ['Enable WebSocket proxy upgrades', 'Inspect reverse proxy config', 'Confirm backend health and port'],
    checks: ['Check the service proxy headers', 'Inspect gateway logs', 'Confirm socket URL includes wss and the correct host'],
    prevention: 'Validate WebSocket upgrade headers in the reverse proxy and exercise a live socket health check before production release.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['curl -I https://api.example.com/socket', 'kubectl logs', 'npm run dev'],
    difficulty: 'Advanced',
  },
  {
    id: 'memory-limit',
    pattern: 'JavaScript heap out of memory',
    title: 'JavaScript memory limit exceeded',
    summary: 'The build or application process ran out of allowed JavaScript heap memory.',
    whatHappened: 'The process terminated during a build or runtime step when the memory allocation passed a hard heap limit.',
    why: 'The process required more memory because of a large dependency graph, large build context, or memory leak.',
    causes: ['Large project dependency graph', 'Memory leak', 'Large build cache'],
    fixes: ['Increase Node memory limit', 'Clean build cache', 'Profile memory usage and eliminate unnecessary objects'],
    checks: ['Read the heap usage log', 'Check package lock or environment worker memory', 'Run a production build with a memory monitor'],
    prevention: 'Keep dependency graphs lean, build in a clean environment, and add memory-aware production build settings.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['NODE_OPTIONS=--max-old-space-size=4096 npm run build', 'npm run dev', 'npm run clean'],
    difficulty: 'Advanced',
  },
  {
    id: 'file-case-sensitivity',
    pattern: 'Module not found: ./Components/Header.jsx',
    title: 'File case sensitivity mismatch',
    summary: 'The app imported a file using a different letter casing than the file on disk.',
    whatHappened: 'The code imported a component path with a different case and the system or build platform treated the path differently than the local machine.',
    why: 'Case-sensitive file systems fail when the import path uses a mismatch in casing.',
    causes: ['Windows or macOS case-insensitive local session', 'Different case in import path', 'Case mismatch in directory names'],
    fixes: ['Rename the import path to match the file exactly', 'Rename the file to the expected casing', 'Run a production preview on a Linux-like file system'],
    checks: ['Compare the import casing with the file name', 'Check the production build file system case rules', 'Read the project path names'],
    prevention: 'Keep import casing consistent and validate with a deploy environment that is case-sensitive.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['ls src/components', 'grep -R "Components/Header" src', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'circular-dependency',
    pattern: 'Circular dependency detected',
    title: 'Circular dependency detected',
    summary: 'Two or more source modules imported each other in a dependency loop.',
    whatHappened: 'The dependency graph formed a cycle that left one module moving through a parent chain back into itself.',
    why: 'Two modules or services import each other through context, service, and UI object chains.',
    causes: ['Shared service imports UI service', 'AppContext import from components', 'Project service relying on UI layer'],
    fixes: ['Break the cycle by moving shared data flow to a separate service', 'Separate AppContext from UI imports', 'Use layer isolation for UI and infrastructure'],
    checks: ['Inspect the import chain in the error output', 'Review service and context dependency layers', 'Print the module graph'],
    prevention: 'Keep UI elements, data services, and app contexts in isolated boundaries and avoid service mixes across layers.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['npm run build', 'grep -R "import .*App" src', 'npm ls'],
    difficulty: 'Advanced',
  },
  {
    id: 'memory-leak-timers',
    pattern: '1,284 active timers',
    title: 'Memory leak through active timers',
    summary: 'The component created many recurring timers that never finished or were not cleared when unmounted.',
    whatHappened: 'A timer, interval, or scheduler was added repeatedly and left in memory without a matching cleanup path.',
    why: 'The component kept registering intervals during life-cycle updates without disposing them during cleanup.',
    causes: ['setInterval without clearInterval', 'Missing timer cleanup', 'Async simulation loops'],
    fixes: ['Clear all intervals in a component cleanup function', 'Use state machine or queue to reduce repeated timers', 'Limit interval creation if a request is still repeated'],
    checks: ['Run debug timers inspection', 'Confirm cleanup removes the interval', 'Inspect whether the simulator is still active'],
    prevention: 'Always pair interval creation with cleanup and keep the component lifecycle aware of canceling background timers.',
    relatedTutorials: ['Troubleshooting'],
    commands: ['grep -R "setInterval" src', 'npm run dev', 'npm run build'],
    difficulty: 'Intermediate',
  },
  {
    id: 'health-check-timeout',
    pattern: 'DEPLOYMENT HEALTH CHECK FAILED',
    title: 'Health check timeout',
    summary: 'The deployment health endpoint did not return a valid response before the deployment timeout was reached.',
    whatHappened: 'The production deployment attempted a health check and passed the timeout budget without receiving a response.',
    why: 'The application or service failed to become healthy from the traffic endpoint within the configured health window.',
    causes: ['Endpoint missing response', 'Server startup failed', 'Database or service dependency not ready'],
    fixes: ['Check the deployment logs', 'Inspect the /health route and startup command', 'Rollback or restart the new release'],
    checks: ['Curl the health endpoint', 'Inspect a service dashboard resource', 'Check the container or service readiness report'],
    prevention: 'Health checks should verify the expected route and dependency chain before a deployment is marked ready.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['curl /health', 'docker logs', 'kubectl rollout status'],
    difficulty: 'Advanced',
  },
  {
    id: 'bad-production-start-command',
    pattern: 'Missing script: "server"',
    title: 'Bad production start command',
    summary: 'The deploy or package command tried to run a package script that the project did not define.',
    whatHappened: 'The runtime attempted to start the app through npm run server but the package manifest only exposed dev, build, and preview scripts.',
    why: 'The deployment command did not match the available package scripts and the project lacked a production server script.',
    causes: ['Wrong script name in package.json', 'Production command mismatch', 'Missing server or start script'],
    fixes: ['Add a server or start script in package.json', 'Use npm run preview or npm run dev as appropriate', 'Update deployment command to a valid npm lifecycle'],
    checks: ['Read package.json scripts', 'Match the deployment command to available scripts', 'Validate the command locally'],
    prevention: 'Keep deployment commands and package.json scripts in sync and validate the production command before publishing.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['npm run dev', 'npm run build', 'npm run preview'],
    difficulty: 'Intermediate',
  },
  {
    id: 'git-detached-head',
    pattern: 'HEAD detached at',
    title: 'Git detached HEAD state',
    summary: 'The repository is currently checked out at an exact commit instead of a named branch.',
    whatHappened: 'The repository ended in a detached HEAD state after a checkout, revert, or debugging workflows.',
    why: 'The branch pointer and the current commit pointer no longer match a normal pushable branch state.',
    causes: ['Detached checkout from a commit', 'Manual repo navigation', 'Branch reset or rebase operation'],
    fixes: ['Checkout a branch with git switch -c or git checkout main', 'Create a branch from the detached commit', 'Commit work before switching history'],
    checks: ['Run git status', 'Check git branch --show-current', 'Compare branch names and detached commit id'],
    prevention: 'Avoid editing without a branch checked out and keep branch-safe commands in your normal Git workflow.',
    relatedTutorials: ['Connect Your Code to GitHub'],
    commands: ['git switch -c feature/fix', 'git checkout main', 'git status'],
    difficulty: 'Beginner',
  },
  {
    id: 'git-rebase-conflict',
    pattern: 'CONFLICT (content):',
    title: 'Git rebase conflict',
    summary: 'A rebase operation paused because a file changed in sequence and the patch could not be applied cleanly.',
    whatHappened: 'Git replayed commits during a rebase and stopped at a conflict in a shared file.',
    why: 'The patch order and file content changed too much between commit history and the current branch sequence.',
    causes: ['Multiple commits touching same file', 'Branch divergence', 'Rebase patch conflict'],
    fixes: ['Resolve the conflict markers', 'git add the resolved file', 'git rebase --continue'],
    checks: ['Inspect git status and conflicted files', 'Read the conflict headers', 'Compare the current file with upstream base'],
    prevention: 'Keep commit history clean, update the branch frequently, and rebase only after resolving known shared-file changes.',
    relatedTutorials: ['Connect Your Code to GitHub'],
    commands: ['git status', 'git add .', 'git rebase --continue'],
    difficulty: 'Intermediate',
  },
  {
    id: 'git-large-file',
    pattern: 'exceeds the repository file size limit',
    title: 'Git large file rejected by remote policy',
    summary: 'The remote rejected a push because the file size exceeded the repository file policy.',
    whatHappened: 'The remote repository found a large file in the push and blocked the upload due to fit policies.',
    why: 'The repository does not accept a heavy binary asset or video file as a tracked file without Git LFS or another storage strategy.',
    causes: ['Large asset committed directly', 'Missing Git LFS hooks', 'Repository storage policy'],
    fixes: ['Use Git LFS for binary assets', 'Remove the large file and track a smaller asset', 'Update the repository policy'],
    checks: ['Check git ls-files for large files', 'Review remote repository policy', 'Inspect the asset folder before pushing'],
    prevention: 'Track large media assets with Git LFS or an object storage system instead of pushing direct file history.',
    relatedTutorials: ['Connect Your Code to GitHub'],
    commands: ['git lfs track "*.mp4"', 'git add .', 'git push origin main'],
    difficulty: 'Intermediate',
  },
  {
    id: 'deployment-rollback',
    pattern: 'Rollback: IN PROGRESS',
    title: 'Deployment rollback',
    summary: 'The production deployment health check or service route failed and the system attempted to return the last-known-good version.',
    whatHappened: 'The release workflow passed build and app-level checks but the health endpoint failed, so the deployment started a fallback rollback.',
    why: 'The new deployment was healthy enough to start but not healthy enough to support traffic or production health checks.',
    causes: ['Health endpoint failure', 'Database readiness issue', 'Service dependency still unavailable'],
    fixes: ['Inspect production logs and health endpoint behavior', 'Re-run the deployment after correcting runtime dependencies', 'Confirm environment and database values'],
    checks: ['Read the health endpoint output and logs', 'Compare the new deployment config with the last successful version', 'Inspect roll-forward and rollback conditions'],
    prevention: 'Validate deployment health earlier, include environment and dependency smoke tests, and require a rollback-safe production fact-check before a release.',
    relatedTutorials: ['Deploy GitHub to Render'],
    commands: ['curl /health', 'kubectl logs', 'npm run build'],
    difficulty: 'Advanced',
  },
  {
    id: 'boss-fight-deploy-error',
    pattern: 'CRITICAL DEPLOYMENT ERROR',
    title: 'Critical deployment error with secondary health issue',
    summary: 'The deployment passed build and application startup checks but failed the health endpoint with a database timeout in the same incident.',
    whatHappened: 'The app reached production startup and the health resource failed, revealing both an API health error and a database timeout.',
    why: 'An upstream dependency chain failed beneath the app while the release was otherwise able to move through installation and startup.',
    causes: ['Production endpoint health issue', 'Database request timeout', 'Dependency chain failure'],
    fixes: ['Inspect /api/health logs', 'Check database connection pool and timeout settings', 'Rollback the deployment and verify DB connectivity'],
    checks: ['Inspect the API health endpoint', 'Check the production database pool health', 'Review deployment rollback messages'],
    prevention: 'Add deployment smoke checks for a health endpoint, database connectivity, and environment variable correctness before production release.',
    relatedTutorials: ['Deploy GitHub to Render', 'Troubleshooting'],
    commands: ['curl /api/health', 'psql -c "SHOW pool"', 'npm run build'],
    difficulty: 'Advanced',
  },
]

const STORAGE_KEY = 'devdeploy-error-history-v1'

export function explainError(errorMessage) {
  const text = String(errorMessage || '').toLowerCase()
  const match = errorCatalog.find((item) => text.includes(item.pattern.toLowerCase()))

  if (!match) {
    return {
      title: 'Unrecognized error',
      summary: 'The analyzer needs more context before it can identify this error.',
      whatHappened: 'The exact message is not in the local database yet.',
      why: 'This usually means the project dependency or tool version is different from the expected setup.',
      causes: ['Unknown command or environment mismatch', 'Tooling version mismatch', 'Project setup issue'],
      fixes: ['Check the exact command output', 'Review project config', 'Compare with the tutorial steps'],
      checks: ['Copy the complete error including the command above it', 'Note which folder and environment produced it', 'Check the tool version shown in the terminal'],
      prevention: 'Keep the full error output and the command that produced it together when troubleshooting.',
      relatedTutorials: ['Troubleshooting', 'Deploy GitHub to Render'],
      commands: ['npm install', 'npm run build', 'git status'],
      difficulty: 'Intermediate',
    }
  }

  return match
}

export function getErrorHistory() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? JSON.parse(raw) : []
  } catch (error) {
    console.warn('Error history unavailable', error)
    return []
  }
}

export function saveErrorHistory(entry) {
  try {
    const history = getErrorHistory()
    history.push({
      ...entry,
      date: new Date().toISOString(),
    })
    localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
    return history
  } catch (error) {
    console.warn('Unable to save error history', error)
    return []
  }
}
